FROM percona:latest

MAINTAINER Alexandr Zayats <alzay@ciklum.com>

COPY conf.d/custom.cnf /etc/mysql/conf.d/custom.cnf

#RUN echo "upstream php-upstream { server php:9000; }" > /etc/nginx/conf.d/upstream.conf
#CMD ["nginx"]
#EXPOSE 3306
