network.host: 0.0.0.0

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
#discovery.zen.minimum_master_nodes: 1
#bootstrap.memory_lock: true

cluster.name: test
#node.name: elastic
#discovery.zen.ping.unicast.hosts: ["elastic-master", "elasticsearch", "elastic-data"]

#node.master: false
#node.ingest: false
#node.data: false
