FROM docker.elastic.co/elasticsearch/elasticsearch:6.2.3

COPY --chown=elasticsearch:elasticsearch config/elastic /usr/share/elasticsearch/config
COPY config/logrotate /etc/logrotate.d/elasticsearch
COPY elastic-entrypoint.sh /
COPY docker-entrypoint.sh /
COPY docker-healthcheck /usr/local/bin/

WORKDIR /usr/share/elasticsearch

ENV PATH /usr/share/elasticsearch/bin:$PATH
ENV ES_TMPDIR /usr/share/elasticsearch/tmp

ENTRYPOINT ["/elastic-entrypoint.sh"]
#ENTRYPOINT ["/docker-entrypoint.sh"]
