version: '3.5'

services:
  management:
    image: registry.ciklum.net/rabbitmq/rabbit:3.9.2
    hostname: management
    environment:
      RABBITMQ_ERLANG_COOKIE: abcdefg
      RABBITMQ_DEFAULT_USER: arvi
      RABBITMQ_DEFAULT_PASS: arvini12
#    ports:
#      - "5672:5672"
#      - "15672:15672"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.rabbit == true]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 15672
        traefik.enable: 'true'
        traefik.docker.network: 'lb_multi-host-network'
        traefik.frontend.rule: "Host:manager.rabbit.pa.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      rabbit:
      lb_multi-host-network:

  PA_Integration_Virtual_Host_Dev:
    image: registry.ciklum.net/rabbitmq/rabbit:3.9.2
    hostname: PA_Integration_Virtual_Host_Dev
    depends_on:
      - management
    environment:
      RABBITMQ_ERLANG_COOKIE: abcdefg
      CLUSTER_WITH: management
#      ENABLE_RAM: 'true'
      RABBITMQ_DEFAULT_USER: arvi
      RABBITMQ_DEFAULT_PASS: arvini12
#    ports:
#      - "5673:5672"
#      - "15673:15672"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.rabbit == true]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 5672
        traefik.enable: 'true'
        traefik.docker.network: 'lb_multi-host-network'
        traefik.frontend.rule: "Host:dev.rabbit.pa.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      rabbit:
      lb_multi-host-network:

  PA_Integration_Virtual_Host_Int:
    image: registry.ciklum.net/rabbitmq/rabbit:3.9.2
    hostname: PA_Integration_Virtual_Host_Int
    depends_on:
      - management
      - PA_Integration_Virtual_Host_Dev
    environment:
      RABBITMQ_ERLANG_COOKIE: abcdefg
      CLUSTER_WITH: management
#      ENABLE_RAM: 'true'
      RABBITMQ_DEFAULT_USER: arvi
      RABBITMQ_DEFAULT_PASS: arvini12
#    ports:
#      - "5673:5672"
#      - "15673:15672"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.rabbit == true]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 5672
        traefik.enable: 'true'
        traefik.docker.network: 'lb_multi-host-network'
        traefik.frontend.rule: "Host:int.rabbit.pa.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      rabbit:
      lb_multi-host-network:

  PA_Integration_Virtual_Host_Qa:
    image: registry.ciklum.net/rabbitmq/rabbit:3.9.2
    hostname: PA_Integration_Virtual_Host_Qa
    depends_on:
      - management
      - PA_Integration_Virtual_Host_Int
      - PA_Integration_Virtual_Host_Dev
    environment:
      RABBITMQ_ERLANG_COOKIE: abcdefg
      CLUSTER_WITH: management
#      ENABLE_RAM: 'true'
      RABBITMQ_DEFAULT_USER: arvi
      RABBITMQ_DEFAULT_PASS: arvini12
#    ports:
#      - "5673:5672"
#      - "15673:15672"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.rabbit == true]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 5672
        traefik.enable: 'true'
        traefik.docker.network: 'lb_multi-host-network'
        traefik.frontend.rule: "Host:qa.rabbit.pa.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      rabbit:
      lb_multi-host-network:

  PA_Integration_Virtual_Host_Prod:
    image: registry.ciklum.net/rabbitmq/rabbit:3.9.2
    hostname: PA_Integration_Virtual_Host_Prod
    depends_on:
      - management
      - PA_Integration_Virtual_Host_Qa
      - PA_Integration_Virtual_Host_Int
      - PA_Integration_Virtual_Host_Dev
    environment:
      RABBITMQ_ERLANG_COOKIE: abcdefg
      CLUSTER_WITH: management
#      ENABLE_RAM: 'true'
      RABBITMQ_DEFAULT_USER: arvi
      RABBITMQ_DEFAULT_PASS: arvini12
#    ports:
#      - "5673:5672"
#      - "15673:15672"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.rabbit == true]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 5672
        traefik.enable: 'true'
        traefik.docker.network: 'lb_multi-host-network'
        traefik.frontend.rule: "Host:prod.rabbit.pa.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      rabbit:
      lb_multi-host-network:

  PA_Integration_Virtual_Host_Stage:
    image: registry.ciklum.net/rabbitmq/rabbit:3.9.2
    hostname: PA_Integration_Virtual_Host_Stage
    depends_on:
      - management
      - PA_Integration_Virtual_Host_Prod
      - PA_Integration_Virtual_Host_Qa
      - PA_Integration_Virtual_Host_Int
      - PA_Integration_Virtual_Host_Dev
    environment:
      RABBITMQ_ERLANG_COOKIE: abcdefg
      CLUSTER_WITH: management
#      ENABLE_RAM: 'true'
      RABBITMQ_DEFAULT_USER: arvi
      RABBITMQ_DEFAULT_PASS: arvini12
#    ports:
#      - "5673:5672"
#      - "15673:15672"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.rabbit == true]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 5672
        traefik.enable: 'true'
        traefik.docker.network: 'lb_multi-host-network'
        traefik.frontend.rule: "Host:stage.rabbit.pa.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      rabbit:
      lb_multi-host-network:

networks:
  rabbit:
    driver: overlay
  lb_multi-host-network:
    external: true
