version: '3.4'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == manager]
      labels:
        traefik.port: 80
        traefik.enable: 'true'
        traefik.docker.network: 'lb_multi-host-network'
        traefik.frontend.rule: "Host:phpadmin.res.tele2.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'

    environment:
      PMA_HOST: '172.28.27.104'
      PMA_USER: 'tele2'
      PMA_PASSWORD: 'fTTeURvl_LluEhw95'
      PMA_ARBITRARY: 1 # - when set to 1 connection to the arbitrary server will be allowed
#      PMA_HOST #- define address/host name of the MySQL server
#      PMA_VERBOSE #- define verbose name of the MySQL server
#      PMA_PORT #- define port of the MySQL server
#      PMA_HOSTS #- define comma separated list of address/host names of the MySQL servers
#      PMA_VERBOSES #- define comma separated list of verbose names of the MySQL servers
#      PMA_PORTS #- define comma separated list of ports of the MySQL servers
#      PMA_USER and PMA_PASSWORD #- define username to use for config authentication method
#      PMA_ABSOLUTE_URI #- define user-facing URI

    volumes:
     - /sessions

    networks:
      lb_multi-host-network:

networks:
  lb_multi-host-network:
    external: true

