version: '3.4'

volumes:
    percona_data:
        driver: local

services: 
    keystone:
        image: registry.ciklum.net/arvini/keystone:latest
        deploy:
            placement:
                constraints: [node.role != manager]
        environment:
            OS_BOOTSTRAP_USERNAME: admin
            OS_BOOTSTRAP_PASSWORD: keystone
            OS_BOOTSTRAP_SERVICE_NAME: keystone
            OS_BOOTSTRAP_REGION_ID: RegionOne
            OS_BOOTSTRAP_ADMIN_URL: http://keystone:5000/v3
            OS_BOOTSTRAP_PUBLIC_URL: http://keystone:5000/v3
            OS_BOOTSTRAP_INTERNAL_URL: http://keystone:5000/v3
            KEYSTONE_DATABASE_CONNECTION: mysql+pymysql://keystone:sd2324lgj_fjg;45KJLr!@keystone-database/keystone
            KEYSTONE_CACHE_HOST: keystone-cache:11211
        ports:
            - 5000:5000
        depends_on:
            - keystone-database
            - keystone-cache
        networks:
            openstack:

    keystone-cache:
        image: memcached
        deploy:
            placement:
                constraints:
                    - node.hostname == minio-node2
        networks:
            openstack:

    controller:
        image: registry.ciklum.net/arvini/proxy:latest
        deploy:
            placement:
                constraints: [node.role == manager]
        ports:
            - 8080:8080
        entrypoint:
        - ifconfig
        - eth0
        - 172.172.238.5
        - netmask
        - 255.255.255.0
        - up
        - &&
        - /usr/bin/swift-proxy-server
        - /etc/swift/proxy-server.conf

        networks:
            openstack:
                ipv4_address: '172.172.238.5'

    storage1:
        image:  registry.ciklum.net/arvini/storage:1309
        deploy:
            placement:
                constraints: 
                    - node.role != manager
                    - node.hostname == minio-node4
        entrypoint: 
        - ifconfig
        - eth0
        - 172.172.238.10
        - netmask
        - 255.255.255.0
        - up
        - &&
        - /usr/bin/swift-object-replicator 
        - /etc/swift/object-server.conf
        networks:
            openstack:
                ipv4_address: '172.172.238.10'

    storage2:
        image:  registry.ciklum.net/arvini/storage:1309
        deploy:
            placement:
                constraints: 
                    - node.role != manager
                    - node.hostname == minio-node3
        entrypoint:
        - ifconfig
        - eth0
        - 172.172.238.20
        - netmask
        - 255.255.255.0
        - up
        - &&
        - /usr/bin/swift-object-replicator 
        - /etc/swift/object-server.conf
        networks:
            openstack:
                ipv4_address: '172.172.238.20'
        
    keystone-database:
        image: percona
        deploy:
            placement:
                constraints:
                    - node.hostname == minio-node2
            mode: replicated
            replicas: 1
        volumes:
            - percona_data:/var/lib/mysql
        environment:
#            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: keystone
            MYSQL_USER: keystone
            MYSQL_PASSWORD: 'sd2324lgj_fjg;45KJLr!'
            MYSQL_ROOT_PASSWORD: 'comcbidz'
        networks:
            openstack:

    horizon:
        image: registry.ciklum.net/arvini/horizon:latest
        deploy:
            placement:
                constraints: [node.role == manager]
        ports:
            - 8083:80
        depends_on:
            - keystone
        networks:
            openstack:
#        labels:
#            traefik.port: 5001
#            traefik.enable: 'true'
#            traefik.docker.network: 'proxy_arvini'
#            traefik.frontend.rule: "Host:app.int.pa.pp.ciklum.com"
#            traefik.backend.loadbalancer.swarm: 'true'

networks:
    openstack:
        driver: overlay
#        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
#       external:
#           name: lb_multi-host-network

