version: '3.4'

volumes:
    openstack:
        external: true
    storage_1:
        driver: local
    storage_2:
        driver: local

services: 
    storage:
        image: registry.ciklum.net/arvini/storage:02031800
        deploy:
            placement:
                constraints: 
                    - node.role != manager
            mode: replicated
            replicas: 2
        environment:
            - "affinity:container!=storage*"
        volumes:
            - type: volume
              source: openstack
              target: /etc/swift/initial
              volume:
                nocopy: false
            - storage_1:/srv/node/sdb
            - storage_2:/srv/node/sdc

        command: /usr/bin/entrypoint
        extra_hosts:
            - "controller:172.28.27.40"
        networks:
            openstack:
#                ipv4_address: 172.16.238.13

    horizon:
        image: registry.ciklum.net/arvini/horizon:latest
        deploy:
            placement:
                constraints: [node.role == manager]
        ports:
            - 8083:80
        extra_hosts:
            - "controller:172.28.27.40"
        networks:
            openstack:
#        labels:
#            traefik.port: 5001
#            traefik.enable: 'true'
#            traefik.docker.network: 'proxy_arvini'
#            traefik.frontend.rule: "Host:app.int.pa.pp.ciklum.com"
#            traefik.backend.loadbalancer.swarm: 'true'

networks:
    openstack:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
#       external:
#           name: lb_multi-host-network

