version: '3.4'

services:
  minio1:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    volumes:
      - type: volume
        source: minio-data
        target: /export
        volume:
          nocopy: true
    ports:
      - 9000:9000
    networks:
      - lb_proxy
    deploy:
#      replicas: 2
      placement:
        constraints:
          - node.hostname == minio-manager
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 9000
        traefik.enable: 'true'
        traefik.docker.network: 'lb_proxy'
        traefik.frontend.rule: "HostRegexp:{subdomain:[a-z]+}.minio.int.arvini2.pp.ciklum.com; Host:minio.int.arvini2.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
        traefik.backend.loadbalancer.method: 'drr'
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    volumes:
      - type: volume
        source: minio-data
        target: /export
        volume:
          nocopy: true
    networks:
      - lb_proxy
    deploy:
      placement:
        constraints:
          - node.hostname == minio-node2
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 9000
        traefik.enable: 'true'
        traefik.docker.network: 'lb_proxy'
        traefik.frontend.rule: "HostRegexp:{subdomain:[a-z]+}.minio.int.arvini2.pp.ciklum.com; Host:minio.int.arvini2.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
        traefik.backend.loadbalancer.method: 'drr'
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio3:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    volumes:
      - type: volume
        source: minio-data
        target: /export
        volume:
          nocopy: true
    networks:
      - lb_proxy
    deploy:
      placement:
        constraints:
          - node.hostname == minio-node3
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 9000
        traefik.enable: 'true'
        traefik.docker.network: 'lb_proxy'
        traefik.frontend.rule: "HostRegexp:{subdomain:[a-z]+}.minio.int.arvini2.pp.ciklum.com; Host:minio.int.arvini2.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
        traefik.backend.loadbalancer.method: 'drr'
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio4:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    volumes:
      - type: volume
        source: minio-data
        target: /export
        volume:
          nocopy: true
    networks:
      - lb_proxy
    deploy:
      placement:
        constraints:
          - node.hostname == minio-node4
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.port: 9000
        traefik.enable: 'true'
        traefik.docker.network: 'lb_proxy'
        traefik.frontend.rule: "HostRegexp:{subdomain:[a-z]+}.minio.int.arvini2.pp.ciklum.com; Host:minio.int.arvini2.pp.ciklum.com"
        traefik.backend.loadbalancer.swarm: 'true'
        traefik.backend.loadbalancer.method: 'drr'
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

volumes:
    minio-data:

networks:
  lb_proxy:
    external: true

secrets:
  secret_key:
    external: true
  access_key:
    external: true
