version: '3.4'

services:
  portainer:
    image: portainer/portainer
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data
    ports:
      - 8082:9000
    labels:
      traefik.port: 9000
      traefik.enable: 'true'
      traefik.docker.network: 'lb_proxy'
      traefik.backend: "manager_portainer"
      traefik.frontend.rule: 'Host:portainer-minio.devops.pp.ciklum.com'
    networks:
      - lb_proxy

networks:
  lb_proxy:
    external: true
