version: '3.4'

services:
  traefik:
    image: traefik
    command: 
      - --web 
      - --docker 
      - --docker.swarmmode 
      - --docker.watch 
      - --docker.domain=arvini
      - --entryPoints=Name:http Address::80
      - --entryPoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --logLevel=DEBUG
    ports:
      - "80:80/tcp"
      - "8080:8080/tcp"
      - "443:443/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /dev/null:/traefik.toml
#    labels:
#      - "traefik.enable=false"
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure

networks:
  proxy:
    driver: overlay
